#pragma once

// NOTE: file is generated by CMake

namespace sentinel::platform::version
{
  constexpr const char* str()
  {
    return "1.0.0";
  }

  constexpr unsigned major()
  {
    return 1;
  }

  constexpr unsigned minor()
  {
    return 0 +0;
  }

  constexpr unsigned patch()
  {
    return 0 +0;
  }

  constexpr unsigned tweak()
  {
    return  +0;
  }
}
